# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Yc


class _Datastorage(_Yc):
    _type = "datastorage"
    _icon_dir = "resources/yc/datastorage"


class DataProc(_Datastorage):
    _icon = "data-proc.png"


class DataTransfer(_Datastorage):
    _icon = "data-transfer.png"


class Datalens(_Datastorage):
    _icon = "datalens.png"


class ManagedClickhouse(_Datastorage):
    _icon = "managed-clickhouse.png"


class ManagedElasticsearch(_Datastorage):
    _icon = "managed-elasticsearch.png"


class ManagedKafka(_Datastorage):
    _icon = "managed-kafka.png"


class ManagedMongodb(_Datastorage):
    _icon = "managed-mongodb.png"


class ManagedMysql(_Datastorage):
    _icon = "managed-mysql.png"


class ManagedPostgresql(_Datastorage):
    _icon = "managed-postgresql.png"


class ManagedRedis(_Datastorage):
    _icon = "managed-redis.png"


class ManagedSqlserver(_Datastorage):
    _icon = "managed-sqlserver.png"


class Mdb(_Datastorage):
    _icon = "mdb.png"


# Aliases
