# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Yc


class _Infrastructure(_Yc):
    _type = "infrastructure"
    _icon_dir = "resources/yc/infrastructure"


class CertificateManager(_Infrastructure):
    _icon = "certificate-manager.png"


class Compute(_Infrastructure):
    _icon = "compute.png"


class ContainerRegistry(_Infrastructure):
    _icon = "container-registry.png"


class DdosProtection(_Infrastructure):
    _icon = "ddos-protection.png"


class IAM(_Infrastructure):
    _icon = "iam.png"


class InstanceGroup(_Infrastructure):
    _icon = "instance-group.png"


class Interconnect(_Infrastructure):
    _icon = "interconnect.png"


class KMS(_Infrastructure):
    _icon = "kms.png"


class LoadBalancer(_Infrastructure):
    _icon = "load-balancer.png"


class ManagedKubernetes(_Infrastructure):
    _icon = "managed-kubernetes.png"


class ManagementConsole(_Infrastructure):
    _icon = "management-console.png"


class Monitoring(_Infrastructure):
    _icon = "monitoring.png"


class ObjectStorage(_Infrastructure):
    _icon = "object-storage.png"


class ResourceManager(_Infrastructure):
    _icon = "resource-manager.png"


class VPC(_Infrastructure):
    _icon = "vpc.png"


# Aliases

S3 = ObjectStorage
MK8s = ManagedKubernetes
Lb = LoadBalancer
IG = InstanceGroup
