# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Yc


class _Ml(_Yc):
    _type = "ml"
    _icon_dir = "resources/yc/ml"


class Api(_Ml):
    _icon = "api.png"


class Datasphere(_Ml):
    _icon = "datasphere.png"


class Locator(_Ml):
    _icon = "locator.png"


class Speechkit(_Ml):
    _icon = "speechkit.png"


class Translate(_Ml):
    _icon = "translate.png"


class Vision(_Ml):
    _icon = "vision.png"


# Aliases
